### ISSUE TITLE
Make docs website from automatically generated documentation

### ISSUE THREAD

**Issue by markdboyd** [developmentseed/cdk-seed#4]
`npm run docgen` generates per package docs. It would be nice to somehow automatically combine these docs into a website for cdk-seed.

**Comment by alukach** [comment]
## Dev Notes

Working branch: https://github.com/developmentseed/cdk-seed/tree/documentation-generation

TODO:

- [x] Update doc generation of just internal packages
- [x] Setup Jekyll
- [x] Enable [just-the-docs](https://pmarsceill.github.io/just-the-docs/) theme
- [ ] ~Enable [Heading Anchors and Table of Contents](https://pure-liquid.allejo.org/)~ _Not necessary, comes for free with Just The Docs theme_

**Comment by alukach** [comment]
Resolved by #10
